server:
    host: 0.0.0.0
    port: 8787
    startup_refresh: false
admin:
    username: admin
    password: ""
    password_hash: scrypt$9e0dd155ac341fd1897c54cee3908452$359d55ea67c15df9da5124c32db431bf2c9d0783f24f3e9a60d290b8102b2a5f9432e82d0137e1f1586bad7b550a1705d9f0d54d7f4756ac2e8fdb538bb6ee6d
    session_secret: ""
    session_ttl_hours: 12
runtime:
    workdir: ../runtime
    mihomo_binary: mihomo
    external_controller: http://127.0.0.1:9090
    external_secret: ""
    render_only: true
subscriptions:
    - name: airport-main
      type: mihomo-http
      url: https://example.com/subscription
      interval: 3600
      enabled: true
      health_check_url: https://www.gstatic.com/generate_204
      health_check_interval: 300
    - name: hitmux
      type: mihomo-http
      url: https://hitmux.org/download/l_10_35c28n5n41432.yaml
      interval: 3600
      enabled: true
      health_check_url: https://www.gstatic.com/generate_204
      health_check_interval: 300
egress_groups:
    - name: egress-us-auto
      provider: airport-main
      mode: auto
      filter: (?i)美|us|united states|america
      exclude_filter: ""
      health_check_url: https://www.gstatic.com/generate_204
      interval: 300
listeners: []
