// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {axis} from '../models';

export function ActivateMihomoVersion(arg1:string):Promise<Record<string, any>>;

export function AddEgressGroup(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddLandingProxy(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddListener(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddSubscription(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddTransitRoute(arg1:Record<string, any>):Promise<Record<string, any>>;

export function BootstrapAdmin(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeleteEgressGroup(arg1:string):Promise<Record<string, any>>;

export function DeleteLandingProxy(arg1:string):Promise<Record<string, any>>;

export function DeleteListener(arg1:string):Promise<Record<string, any>>;

export function DeleteSubscription(arg1:string):Promise<Record<string, any>>;

export function DeleteTransitRoute(arg1:string):Promise<Record<string, any>>;

export function DownloadMihomoVersion(arg1:string):Promise<Record<string, any>>;

export function GetBootstrapStatus():Promise<axis.BootstrapStatus>;

export function GetConfig():Promise<Record<string, any>>;

export function GetController():Promise<Record<string, any>>;

export function GetEvents():Promise<Array<axis.EventEntry>>;

export function GetGroups():Promise<Array<axis.GroupView>>;

export function GetLandingProxies():Promise<Array<axis.LandingProxyView>>;

export function GetListeners():Promise<Array<axis.ListenerView>>;

export function GetMihomoVersions():Promise<axis.MihomoVersionsResponse>;

export function GetProviders():Promise<Array<Record<string, any>>>;

export function GetRenderedConfig():Promise<Record<string, any>>;

export function GetRuntimePreflight():Promise<axis.RuntimePreflightSnapshot>;

export function GetSession():Promise<Record<string, any>>;

export function GetSetupState():Promise<axis.SetupState>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTransitRoutes():Promise<Array<axis.TransitRouteView>>;

export function HealthcheckGroup(arg1:string):Promise<Record<string, any>>;

export function HealthcheckTransitRoute(arg1:string):Promise<Record<string, any>>;

export function InstallMihomoVersion(arg1:string):Promise<Record<string, any>>;

export function Login(arg1:Record<string, any>):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, any>>;

export function ProbeController():Promise<Record<string, any>>;

export function RefreshProvider(arg1:string):Promise<Record<string, any>>;

export function ReloadRuntime():Promise<Record<string, any>>;

export function SaveConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SelectGroup(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function ToggleSubscription(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateEgressGroup(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateLandingProxy(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateListener(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdatePassword(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateTransitRoute(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;
