// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateMihomoVersion(arg1) {
  return window['go']['main']['EngineBindings']['ActivateMihomoVersion'](arg1);
}

export function AddEgressGroup(arg1) {
  return window['go']['main']['EngineBindings']['AddEgressGroup'](arg1);
}

export function AddLandingProxy(arg1) {
  return window['go']['main']['EngineBindings']['AddLandingProxy'](arg1);
}

export function AddListener(arg1) {
  return window['go']['main']['EngineBindings']['AddListener'](arg1);
}

export function AddNodeSource(arg1) {
  return window['go']['main']['EngineBindings']['AddNodeSource'](arg1);
}

export function AddPublication(arg1) {
  return window['go']['main']['EngineBindings']['AddPublication'](arg1);
}

export function AddRoute(arg1) {
  return window['go']['main']['EngineBindings']['AddRoute'](arg1);
}

export function AddSubscription(arg1) {
  return window['go']['main']['EngineBindings']['AddSubscription'](arg1);
}

export function AddTransitRoute(arg1) {
  return window['go']['main']['EngineBindings']['AddTransitRoute'](arg1);
}

export function BootstrapAdmin(arg1) {
  return window['go']['main']['EngineBindings']['BootstrapAdmin'](arg1);
}

export function BuildLLMProposal(arg1) {
  return window['go']['main']['EngineBindings']['BuildLLMProposal'](arg1);
}

export function CheckLocalNode(arg1) {
  return window['go']['main']['EngineBindings']['CheckLocalNode'](arg1);
}

export function DeleteEgressGroup(arg1) {
  return window['go']['main']['EngineBindings']['DeleteEgressGroup'](arg1);
}

export function DeleteLandingProxy(arg1) {
  return window['go']['main']['EngineBindings']['DeleteLandingProxy'](arg1);
}

export function DeleteListener(arg1) {
  return window['go']['main']['EngineBindings']['DeleteListener'](arg1);
}

export function DeleteNodeSource(arg1) {
  return window['go']['main']['EngineBindings']['DeleteNodeSource'](arg1);
}

export function DeletePublication(arg1) {
  return window['go']['main']['EngineBindings']['DeletePublication'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['main']['EngineBindings']['DeleteRoute'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['EngineBindings']['DeleteSubscription'](arg1);
}

export function DeleteTransitRoute(arg1) {
  return window['go']['main']['EngineBindings']['DeleteTransitRoute'](arg1);
}

export function DownloadMihomoVersion(arg1) {
  return window['go']['main']['EngineBindings']['DownloadMihomoVersion'](arg1);
}

export function GetBootstrapStatus() {
  return window['go']['main']['EngineBindings']['GetBootstrapStatus']();
}

export function GetConfig() {
  return window['go']['main']['EngineBindings']['GetConfig']();
}

export function GetController() {
  return window['go']['main']['EngineBindings']['GetController']();
}

export function GetCoreCapabilities() {
  return window['go']['main']['EngineBindings']['GetCoreCapabilities']();
}

export function GetEvents() {
  return window['go']['main']['EngineBindings']['GetEvents']();
}

export function GetGroups() {
  return window['go']['main']['EngineBindings']['GetGroups']();
}

export function GetLandingProxies() {
  return window['go']['main']['EngineBindings']['GetLandingProxies']();
}

export function GetListeners() {
  return window['go']['main']['EngineBindings']['GetListeners']();
}

export function GetLocalNodeBaotaConfig(arg1) {
  return window['go']['main']['EngineBindings']['GetLocalNodeBaotaConfig'](arg1);
}

export function GetLocalNodeConnection(arg1) {
  return window['go']['main']['EngineBindings']['GetLocalNodeConnection'](arg1);
}

export function GetMihomoVersions() {
  return window['go']['main']['EngineBindings']['GetMihomoVersions']();
}

export function GetNodeSources() {
  return window['go']['main']['EngineBindings']['GetNodeSources']();
}

export function GetProviders() {
  return window['go']['main']['EngineBindings']['GetProviders']();
}

export function GetPublications() {
  return window['go']['main']['EngineBindings']['GetPublications']();
}

export function GetRenderedConfig() {
  return window['go']['main']['EngineBindings']['GetRenderedConfig']();
}

export function GetRoutes() {
  return window['go']['main']['EngineBindings']['GetRoutes']();
}

export function GetRuntimePreflight() {
  return window['go']['main']['EngineBindings']['GetRuntimePreflight']();
}

export function GetSession() {
  return window['go']['main']['EngineBindings']['GetSession']();
}

export function GetSetupState() {
  return window['go']['main']['EngineBindings']['GetSetupState']();
}

export function GetStatus() {
  return window['go']['main']['EngineBindings']['GetStatus']();
}

export function GetTransitRoutes() {
  return window['go']['main']['EngineBindings']['GetTransitRoutes']();
}

export function GetUsage() {
  return window['go']['main']['EngineBindings']['GetUsage']();
}

export function HealthcheckGroup(arg1) {
  return window['go']['main']['EngineBindings']['HealthcheckGroup'](arg1);
}

export function HealthcheckTransitRoute(arg1) {
  return window['go']['main']['EngineBindings']['HealthcheckTransitRoute'](arg1);
}

export function InstallMihomoVersion(arg1) {
  return window['go']['main']['EngineBindings']['InstallMihomoVersion'](arg1);
}

export function ListLLMModels() {
  return window['go']['main']['EngineBindings']['ListLLMModels']();
}

export function ListLLMModelsWithConfig(arg1) {
  return window['go']['main']['EngineBindings']['ListLLMModelsWithConfig'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['EngineBindings']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['EngineBindings']['Logout']();
}

export function ProbeController() {
  return window['go']['main']['EngineBindings']['ProbeController']();
}

export function RefreshProvider(arg1) {
  return window['go']['main']['EngineBindings']['RefreshProvider'](arg1);
}

export function ReloadRuntime() {
  return window['go']['main']['EngineBindings']['ReloadRuntime']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['EngineBindings']['SaveConfig'](arg1);
}

export function SelectGroup(arg1, arg2) {
  return window['go']['main']['EngineBindings']['SelectGroup'](arg1, arg2);
}

export function TestLLM(arg1) {
  return window['go']['main']['EngineBindings']['TestLLM'](arg1);
}

export function ToggleSubscription(arg1, arg2) {
  return window['go']['main']['EngineBindings']['ToggleSubscription'](arg1, arg2);
}

export function UpdateEgressGroup(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateEgressGroup'](arg1, arg2);
}

export function UpdateLandingProxy(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateLandingProxy'](arg1, arg2);
}

export function UpdateListener(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateListener'](arg1, arg2);
}

export function UpdateNodeSource(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateNodeSource'](arg1, arg2);
}

export function UpdatePassword(arg1) {
  return window['go']['main']['EngineBindings']['UpdatePassword'](arg1);
}

export function UpdatePublication(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdatePublication'](arg1, arg2);
}

export function UpdateRoute(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateRoute'](arg1, arg2);
}

export function UpdateSubscription(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateSubscription'](arg1, arg2);
}

export function UpdateTransitRoute(arg1, arg2) {
  return window['go']['main']['EngineBindings']['UpdateTransitRoute'](arg1, arg2);
}

export function UpdateUsage(arg1) {
  return window['go']['main']['EngineBindings']['UpdateUsage'](arg1);
}
