// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['HostBindings']['CheckForUpdates']();
}

export function GetStatus() {
  return window['go']['main']['HostBindings']['GetStatus']();
}

export function GetUpdaterStatus() {
  return window['go']['main']['HostBindings']['GetUpdaterStatus']();
}

export function OpenControlCenter() {
  return window['go']['main']['HostBindings']['OpenControlCenter']();
}

export function SetAutostart(arg1) {
  return window['go']['main']['HostBindings']['SetAutostart'](arg1);
}
