// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {axis} from '../models';

export function CheckForUpdates():Promise<Record<string, any>>;

export function GetStatus():Promise<axis.HostStatus>;

export function GetUpdaterStatus():Promise<axis.UpdaterStatus>;

export function OpenControlCenter():Promise<Record<string, any>>;

export function SetAutostart(arg1:boolean):Promise<Record<string, any>>;
